### ISSUE TITLE
AwesomeNode::drawSolidRect

### ISSUE THREAD

**Issue by crazyhappygame** [intmainreturn00/AwesomeNode#1]
Hi,

Could you explain why one method call drawSolidPoly and second DrawNode::drawSolidRect
```
void AwesomeNode::drawSolidRect(const Vec2 &p1, const Vec2 &p2, const Vec2 &p3, const Vec2 &p4,
                                const Color4F &color) {
    Vec2 vertices[] = {p1, p2, p3, p4};
    drawSolidPoly(vertices, 4, color);
}

void AwesomeNode::drawSolidRect(const Vec2 &origin, const Vec2 &destination, const Color4F &color) {
    DrawNode::drawSolidRect(origin, destination, color);
}
```

**Comment by intmainreturn00** [comment]
Sorry for the delayed response, could you clarify?
`drawSolidPoly` api works with an array and `drawSolidRect` only with `origin` \ `destination`. 
[docs](https://docs.cocos2d-x.org/api-ref/cplusplus/V3.8/dd/d6a/classcocos2d_1_1_draw_node.html#ad5c24f97274091c6575735fad9c92fc8)
Its a shorthand for 4 point figure.

**Comment by crazyhappygame** [comment]
@intmainreturn00 
Thank you for explanation!
Both function call DrawNode::* methods I thought that one call AwesomeNode::drawSolidPoly and second call DrawNode::drawSolidRec
Maybe it will be better to explicit DrawNode:: everywhere
```
void AwesomeNode::drawSolidRect(const Vec2 &p1, const Vec2 &p2, const Vec2 &p3, const Vec2 &p4,
                                const Color4F &color) {
    Vec2 vertices[] = {p1, p2, p3, p4};
    DrawNode::drawSolidPoly(vertices, 4, color);
}

void AwesomeNode::drawSolidRect(const Vec2 &origin, const Vec2 &destination, const Color4F &color) {
    DrawNode::drawSolidRect(origin, destination, color);
}
```
